// Copyright (c) Robert Garner. All rights reserved.

namespace InsTK.Server.Services.Ollama;

/// <summary>
/// Represents the text generated by Ollama for a submitted prompt.
/// </summary>
/// <param name="Response">The response text returned by Ollama.</param>
public sealed record OllamaGenerateResult(string Response);
