// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227194920_AddSmeQuestionnaireModels")]
    partial class AddSmeQuestionnaireModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Common.Models.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Common.Models.Objective", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentObj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.Curriculum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("TargetEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("TargetStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Curriculums");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QuestionnaireQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireQuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SmeQuestionnaireResponseId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValueNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValueRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SmeQuestionnaireResponseId");

                    b.ToTable("QuestionnaireAnswers");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HelpText")
                        .HasColumnType("TEXT");

                    b.Property<int>("InputType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QuestionnaireSectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireSectionId");

                    b.ToTable("QuestionnaireQuestions");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SmeQuestionnaireId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SmeQuestionnaireId");

                    b.ToTable("QuestionnaireSections");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiredForJob")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SmeQuestionnaireResponseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionOrSpec")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SmeQuestionnaireResponseId");

                    b.ToTable("SmeEquipment");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalOpenEndedPrompt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinalOpenEndedRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("SmeQuestionnaires");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeQuestionnaireResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalOpenEndedAnswer")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PrivacyAcknowledgedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectMatterExpertId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SubmittedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectMatterExpertId");

                    b.ToTable("SmeQuestionnaireResponses");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SmeQuestionnaireResponseId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SmeQuestionnaireResponseId");

                    b.ToTable("SmeSkills");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeSoftware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiredForJob")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SmeQuestionnaireResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SmeQuestionnaireResponseId");

                    b.ToTable("SmeSoftware");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SubjectMatterExpert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurriculumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("SubjectMatterExperts");
                });

            modelBuilder.Entity("CourseObjective", b =>
                {
                    b.Property<string>("CoursesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectivesId")
                        .HasColumnType("TEXT");

                    b.HasKey("CoursesId", "ObjectivesId");

                    b.HasIndex("ObjectivesId");

                    b.ToTable("CourseObjective");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("BLOB");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Server.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionOption", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.QuestionnaireQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionnaireQuestionId");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireAnswer", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.SmeQuestionnaireResponse", null)
                        .WithMany("Answers")
                        .HasForeignKey("SmeQuestionnaireResponseId");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireQuestion", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.QuestionnaireSection", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnaireSectionId");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireSection", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.SmeQuestionnaire", null)
                        .WithMany("Sections")
                        .HasForeignKey("SmeQuestionnaireId");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeEquipment", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.SmeQuestionnaireResponse", null)
                        .WithMany("Equipment")
                        .HasForeignKey("SmeQuestionnaireResponseId");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeQuestionnaire", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.Curriculum", null)
                        .WithMany("Questionnaires")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeQuestionnaireResponse", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.SubjectMatterExpert", null)
                        .WithMany("QuestionnaireResponses")
                        .HasForeignKey("SubjectMatterExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeSkill", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.SmeQuestionnaireResponse", null)
                        .WithMany("Skills")
                        .HasForeignKey("SmeQuestionnaireResponseId");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeSoftware", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.SmeQuestionnaireResponse", null)
                        .WithMany("Software")
                        .HasForeignKey("SmeQuestionnaireResponseId");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SubjectMatterExpert", b =>
                {
                    b.HasOne("Common.Models.SmeQuestionnaire.Curriculum", null)
                        .WithMany("SubjectMatterExperts")
                        .HasForeignKey("CurriculumId");
                });

            modelBuilder.Entity("CourseObjective", b =>
                {
                    b.HasOne("Common.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.Objective", null)
                        .WithMany()
                        .HasForeignKey("ObjectivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<uint>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.Curriculum", b =>
                {
                    b.Navigation("Questionnaires");

                    b.Navigation("SubjectMatterExperts");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.QuestionnaireSection", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeQuestionnaire", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SmeQuestionnaireResponse", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Equipment");

                    b.Navigation("Skills");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("Common.Models.SmeQuestionnaire.SubjectMatterExpert", b =>
                {
                    b.Navigation("QuestionnaireResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
